TCP_PORT_GRPC="9000"
TCP_PORT_TELNET="9999"

[REDIS_CONFIG]    
REDIS_HOST="localhost"
REDIS_PORT="6379"
REDIS_PASSWORD=""

[POSTGRES_CONFIG]
POSTGRES_HOST="localhost"
POSTGRES_PORT=5432
POSTGRES_USER="postgres"
POSTGRES_PASSWORD="123456789"
POSTGRES_DBNAME="mydatabase"  

DEBUG=true